---
kind: pipeline
type: docker # 在 Docker Runner 中运行
name: default

steps:
  - name: build
    image: maven:3.8.3-jdk-8
    volumes:
      - name: maven-data
        path: /root/.m2
    commands:
      - mvn clean install -U -T 4

trigger:
  branch:
    - master

volumes:
  - name: maven-data
    host:
      path: /var/lib/drone_maven
